// adventure.js
// ===== EXERCISE 3: EXTERNAL JAVASCRIPT ADVENTURE =====
// This is the answer key for Exercise 3 - The JavaScript Adventure Story

console.log('╔═══════════════════════════════════════════════════════════╗');
console.log('║                                                           ║');
console.log('║        THE QUEST FOR THE GOLDEN CODE                      ║');
console.log('║        An Interactive JavaScript Adventure                ║');
console.log('║                                                           ║');
console.log('╚═══════════════════════════════════════════════════════════╝');
console.log('');
console.log('');

// ========== PROLOGUE ==========
console.log('═══════════════════════════════════════════════════════════');
console.log('                        PROLOGUE');
console.log('═══════════════════════════════════════════════════════════');
console.log('');
console.log('In a world where code controls everything, there exists');
console.log('a legendary artifact known as the Golden Code...');
console.log('');
console.log('This code is said to have the power to create anything');
console.log('imaginable with just a few lines of JavaScript!');
console.log('');
console.log('You are a young programmer on a quest to find it...');
console.log('');
console.log('🎮 Press F12 to continue your adventure in the console! 🎮');
console.log('');
console.log('');

// ========== CHAPTER 1: THE BEGINNING ==========
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('📖 CHAPTER 1: The Programmer\'s Village');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('You wake up in your small village of Codington.');
console.log('Population:', 127, 'programmers');
console.log('');
console.log('The village elder, Master JavaScript, approaches you:');
console.log('"Young one, you must find the Golden Code!"');
console.log('');
console.log('Master JavaScript gives you:');
console.log('- A laptop with', 8, 'GB of RAM');
console.log('- A guidebook with', 500, 'pages of JavaScript knowledge');
console.log('- A magical USB drive (it has', 256, 'GB of storage!)');
console.log('');
console.log('Total items received:', 3);
console.log('Your inventory weight:', 8 + 500 + 256, 'units');
console.log('');
console.log('✓ Chapter 1 Complete!');
console.log('');
console.log('');

// ========== CHAPTER 2: THE FOREST OF FUNCTIONS ==========
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('🌲 CHAPTER 2: The Forest of Functions');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('You enter a dense forest with', 1000, 'trees.');
console.log('Each tree represents a different JavaScript function!');
console.log('');
console.log('🐉 SUDDENLY! A wild bug appears!');
console.log('Bug Level:', 5);
console.log('Bug HP:', 50);
console.log('');
console.log('You must defeat it with your debugging skills!');
console.log('');
console.log('⚔️ BATTLE SEQUENCE:');
console.log('Your attack power:', 12);
console.log('Number of attacks needed:', 50 / 12);
console.log('Rounded up, that\'s', Math.ceil(50 / 12), 'attacks!');
console.log('');
console.log('Attack 1: Deal', 12, 'damage! Bug HP:', 50 - 12);
console.log('Attack 2: Deal', 12, 'damage! Bug HP:', 50 - 12 - 12);
console.log('Attack 3: Deal', 12, 'damage! Bug HP:', 50 - 12 - 12 - 12);
console.log('Attack 4: Deal', 12, 'damage! Bug HP:', 50 - 12 - 12 - 12 - 12);
console.log('Attack 5: Deal', 12, 'damage! Bug HP:', 50 - 12 - 12 - 12 - 12 - 12);
console.log('');
console.log('💥 VICTORY! Bug defeated!');
console.log('');
console.log('Rewards:');
console.log('- Experience Points (XP):', 100);
console.log('- Gold Coins:', 25);
console.log('- Debug Badge (Level', 1, ')');
console.log('');
console.log('✓ Chapter 2 Complete!');
console.log('');
console.log('');

// ========== CHAPTER 3: THE MOUNTAIN OF ARRAYS ==========
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('⛰️ CHAPTER 3: The Mountain of Arrays');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('You reach a massive mountain with', 10, 'levels.');
console.log('Each level is', 100, 'meters high.');
console.log('Total mountain height:', 10 * 100, 'meters!');
console.log('');
console.log('At each level, you find a treasure chest!');
console.log('');
console.log('🎁 TREASURES FOUND:');
console.log('Level 1:', 10, 'gold coins');
console.log('Level 2:', 20, 'gold coins');
console.log('Level 3:', 30, 'gold coins');
console.log('Level 4:', 40, 'gold coins');
console.log('Level 5:', 50, 'gold coins');
console.log('');
console.log('Pattern: Each level gives', 10, 'more coins than the last!');
console.log('Total coins from first 5 levels:', 10 + 20 + 30 + 40 + 50);
console.log('');
console.log('You also had', 25, 'coins from the forest battle.');
console.log('New total gold:', (10 + 20 + 30 + 40 + 50) + 25, 'coins!');
console.log('');
console.log('💡 Fun Fact: If all 10 levels follow this pattern...');
console.log('Level 6 would have:', 60, 'coins');
console.log('Level 7 would have:', 70, 'coins');
console.log('Level 8 would have:', 80, 'coins');
console.log('Level 9 would have:', 90, 'coins');
console.log('Level 10 would have:', 100, 'coins!');
console.log('Grand total would be:', 10+20+30+40+50+60+70+80+90+100, 'coins!');
console.log('');
console.log('✓ Chapter 3 Complete!');
console.log('');
console.log('');

// ========== CHAPTER 4: THE CASTLE OF LOGIC ==========
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('🏰 CHAPTER 4: The Castle of Logic');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('You arrive at a magnificent castle with', 4, 'towers.');
console.log('Each tower has', 7, 'floors.');
console.log('Total floors in castle:', 4 * 7, 'floors!');
console.log('');
console.log('🚪 THE RIDDLE DOOR:');
console.log('A mysterious door blocks your path.');
console.log('It has', 3, 'locks that require math to open!');
console.log('');
console.log('Lock 1: "What is 15 × 3?"');
console.log('You answer:', 15 * 3, '✓ Correct!');
console.log('');
console.log('Lock 2: "What is 100 - 37?"');
console.log('You answer:', 100 - 37, '✓ Correct!');
console.log('');
console.log('Lock 3: "What is 144 ÷ 12?"');
console.log('You answer:', 144 / 12, '✓ Correct!');
console.log('');
console.log('🎊 All locks opened!');
console.log('Bonus XP for solving riddles:', 150);
console.log('');
console.log('Inside, you find a map!');
console.log('The map shows the Golden Code is only', 5, 'kilometers away!');
console.log('That\'s', 5 * 1000, 'meters!');
console.log('');
console.log('✓ Chapter 4 Complete!');
console.log('');
console.log('');

// ========== CHAPTER 5: THE GOLDEN CODE ==========
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('✨ CHAPTER 5: Discovery of the Golden Code');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('After traveling', 5, 'kilometers, you reach a sacred temple.');
console.log('Golden light pours from the entrance!');
console.log('');
console.log('🌟 YOU FOUND IT! 🌟');
console.log('');
console.log('The Golden Code appears before you:');
console.log('');
console.log('┌─────────────────────────────────────────┐');
console.log('│  console.log("Hello, World!");          │');
console.log('│  console.log("You can create anything!");│');
console.log('│  console.log("Just keep coding!");      │');
console.log('└─────────────────────────────────────────┘');
console.log('');
console.log('The Golden Code whispers its wisdom:');
console.log('"The power was in YOU all along..."');
console.log('"Every console.log() is a spell..."');
console.log('"Every calculation is magic..."');
console.log('"Keep learning, keep building!"');
console.log('');
console.log('✓ Chapter 5 Complete!');
console.log('');
console.log('');

// ========== EPILOGUE ==========
console.log('═══════════════════════════════════════════════════════════');
console.log('                        EPILOGUE');
console.log('═══════════════════════════════════════════════════════════');
console.log('');
console.log('🎉 ADVENTURE COMPLETE! 🎉');
console.log('');
console.log('📊 FINAL STATISTICS:');
console.log('───────────────────────────────────────────────────────────');
console.log('');
console.log('Chapters completed:', 5);
console.log('Total XP earned:', 100 + 150, 'XP');
console.log('Gold collected:', 550, 'coins');
console.log('Bugs defeated:', 1);
console.log('Mountains climbed:', 1);
console.log('Riddles solved:', 3);
console.log('Lines of code written:', 200);
console.log('');
console.log('Distance traveled:');
console.log('- Forest:', 2, 'km');
console.log('- Mountain:', 3, 'km');
console.log('- Castle:', 5, 'km');
console.log('Total distance:', 2 + 3 + 5, 'kilometers =', (2 + 3 + 5) * 1000, 'meters!');
console.log('');
console.log('Time spent on quest:', 3, 'hours =', 3 * 60, 'minutes!');
console.log('');
console.log('═══════════════════════════════════════════════════════════');
console.log('');
console.log('💬 The Golden Code\'s Final Message:');
console.log('');
console.log('"You have learned the basics of JavaScript!"');
console.log('"You can use console.log() to create stories!"');
console.log('"You can use math to solve problems!"');
console.log('"You can organize code in external .js files!"');
console.log('');
console.log('"This is just the beginning of your journey..."');
console.log('"There are", 12, "more lessons ahead!");');
console.log('"Each lesson will teach you new powers!"');
console.log('');
console.log('"Keep coding, young programmer! 🚀"');
console.log('');
console.log('═══════════════════════════════════════════════════════════');
console.log('');
console.log('Thank you for playing!');
console.log('');
console.log('🎓 LESSON PROGRESS: 1 of 13 JavaScript lessons complete!');
console.log('📈 That\'s', Math.round((1 / 13) * 100), '% of Module 3!');
console.log('');
console.log('✨ See you in the next lesson! ✨');
